n = input('Digite algo: ')
print(type(n))
print(n.isalnum())
print(n.isalpha())
print(n.isascii())
print(n.isdigit())
print(n.islower())
print(n.isalnum())
print(n.isdecimal())
print(n.isidentifier())
print(n.isnumeric())
print(n.isprintable())
print(n.isprintable())
